
GENERATED += mpfi-stubs.o

include ../../Makefile

mpfi-stubs.o : mpfi-stubs.c 
	gcc -I $(MPFI_INCLUDE_DIR) -I $(MPFR_INCLUDE_DIR) -c -o $@ $<

OPTS += $(MPFR_OPT) $(MPFI_OPT)

OBJS = $(MPFR_OBJ) $(MPFI_OBJ) 





